### ISSUE TITLE
No animal noises for the possums.

### ISSUE THREAD

**Issue by PossumThatCodes** [lucidinceptor/Awesome-Possums#2]
There aren't any noises when you press g, alt+g, or ctrl+g. Your mouth is animated, but no noise. Unsure if a bug or not, but if there isn't supposed to be sound, it'd be cool if the mod worked with VoiceTrainedSpecies so i could make noise at people.

**Comment by lucidinceptor** [comment]
Sorry about that, just added sounds with the latest update! They're a little silly because I had to modify other animal noises to make them, its basically impossible to find royalty free possum sounds online.
